### PR TITLE
Updated mysql driver.

### PR DESCRIPTION
**Pull request by dartartem**
PR adds support of mysql 8. See:

https://github.com/eventuate-foundation/eventuate-cdc/issues/99
https://github.com/eventuate-foundation/eventuate-cdc/issues/47

### CODE REVIEW

**Comment by BenNeighbour** [comment]
Hi, has this been merged in yet?

**Comment by BenNeighbour** [comment]
If not, would you have to use MySQL 5 with eventuate instead?

**Comment by dartartem** [comment]
Hi @BenNeighbour, no, it is not yet merged for sagas. To work with eventuate sagas you should use MySQL 5.

**Comment by BenNeighbour** [comment]
Okay - also with this framework does everything have to link to one database for PostgresWal and Kafka implementation like the example or is it just for simplicity sake?

**Comment by dartartem** [comment]
@BenNeighbour, sorry, but I do not understand the question

**Comment by BenNeighbour** [comment]
@dartartem sorry, I meant do all the services have to connect to one database for the eventuate sagas to work, or can they be separate

**Comment by dartartem** [comment]
@BenNeighbour, yes, services communicate using events/messages. Some service writes event/message to database, special application (CDC service) reads db logs and sends events/messages to kafka, then other services can subscribe to those events/messages in kafka. Please see https://eventuate.io/ there you can find more info.

**Comment by BenNeighbour** [comment]
@dartartem okay, but shouldn't each service have it's own separate data store? I'm not that bothered about it for my project but just curious

**Comment by dartartem** [comment]
@BenNeighbour it is up to you. Here https://github.com/eventuate-tram/eventuate-tram-examples-customers-and-orders one service works like a view, it keeps data in mongodb. Other 2 services store everything in single db. Yes, example does not use sagas, only tram, but general ideas the same.

**Comment by BenNeighbour** [comment]
@dartartem I'm only referring to the saga example -  I guess database sharding is potentially solution to scalability as well as master space backups to avoid single point of failure

**Comment by dartartem** [comment]
@BenNeighbour again, it is up to you how to configure a database. Eventuate projects only need to write to event/message tables and db should allow cdc to read binlog. Instead of binlog you can use EventuatePolling profile, it queries event/message tables directly.

**Comment by cer** [comment]
> @dartartem okay, but shouldn't each service have its own separate data store? I'm not that bothered about it for my project but just curious

@BenNeighbour Yes, each service can have its own database server if your architecture needs that.  For simplicity the examples use a single database server.

You can have a single CDC for multiple databases or a CDC per database. That's a capacity planning issue.

The closest example is https://github.com/microservices-patterns/ftgo-application/blob/a835e23bb0f3bc92dd712ff48a1510496ecb10fa/docker-compose.yml#L43 - each service has its own database schema (logical database) on the same server.

**Comment by BenNeighbour** [comment]
Thanks Chris, just what I was looking for! I really like your framework by the way!

**Pull request merged**
